import type {
  NERZone,
  SHAPFactor,
  ForecastPoint,
  AlertMessage,
  CitizenReport,
  SitrepData,
} from "@/types";

export const NER_ZONES: NERZone[] = [
  {
    id: "dima-hasao",
    name: "Dima Hasao Highlands",
    district: "Dima Hasao",
    state: "Assam",
    lat: 25.5624,
    lng: 93.0199,
    risk: "CRITICAL",
    riskScore: 92,
    rainfall24h: 187,
    soilMoisture: 94,
    slope: 38,
    trigger: "Extreme rainfall + saturated slopes",
    lastUpdated: "2026-09-10T21:30:00+05:30",
    affectedPopulation: 12400,
    roadBlockages: ["NH-27 km 341-348", "NH-54 km 211"],
    sensors: [
      { id: "S-DH-01", type: "Inclinometer", status: "online", battery: 78 },
      { id: "S-DH-02", type: "Rain Gauge", status: "online", battery: 91 },
      { id: "S-DH-03", type: "Piezometer", status: "degraded", battery: 42 },
    ],
  },
  {
    id: "nh27-lumding-silchar",
    name: "NH-27 Lumding–Silchar",
    district: "Cachar / Hailakandi",
    state: "Assam",
    lat: 25.027,
    lng: 93.005,
    risk: "HIGH",
    riskScore: 76,
    rainfall24h: 142,
    soilMoisture: 86,
    slope: 29,
    trigger: "Debris flow risk on embankment",
    lastUpdated: "2026-09-10T21:15:00+05:30",
    affectedPopulation: 8200,
    roadBlockages: ["NH-27 km 415-422"],
    sensors: [
      { id: "S-NH-01", type: "Accelerometer", status: "online", battery: 65 },
      { id: "S-NH-02", type: "Rain Gauge", status: "online", battery: 88 },
    ],
  },
  {
    id: "champhai",
    name: "Champhai Valley",
    district: "Champhai",
    state: "Mizoram",
    lat: 23.4543,
    lng: 93.3286,
    risk: "HIGH",
    riskScore: 68,
    rainfall24h: 115,
    soilMoisture: 79,
    slope: 34,
    trigger: "Slope instability detected",
    lastUpdated: "2026-09-10T20:45:00+05:30",
    affectedPopulation: 5600,
    roadBlockages: ["AH-1 near Zokhawthar"],
    sensors: [
      { id: "S-CH-01", type: "Inclinometer", status: "online", battery: 82 },
      { id: "S-CH-02", type: "Piezometer", status: "online", battery: 71 },
    ],
  },
  {
    id: "east-khasi-hills",
    name: "East Khasi Hills",
    district: "East Khasi Hills",
    state: "Meghalaya",
    lat: 25.5788,
    lng: 91.8933,
    risk: "MODERATE",
    riskScore: 54,
    rainfall24h: 89,
    soilMoisture: 72,
    slope: 26,
    trigger: "Elevated moisture levels",
    lastUpdated: "2026-09-10T21:00:00+05:30",
    affectedPopulation: 3100,
    roadBlockages: [],
    sensors: [
      { id: "S-EK-01", type: "Rain Gauge", status: "online", battery: 94 },
      { id: "S-EK-02", type: "MEMS Tilt", status: "offline", battery: 5 },
    ],
  },
  {
    id: "mangan",
    name: "Mangan — North Sikkim",
    district: "North Sikkim",
    state: "Sikkim",
    lat: 27.5127,
    lng: 88.5269,
    risk: "MODERATE",
    riskScore: 49,
    rainfall24h: 74,
    soilMoisture: 68,
    slope: 42,
    trigger: "Post-seismic loose debris",
    lastUpdated: "2026-09-10T20:30:00+05:30",
    affectedPopulation: 2400,
    roadBlockages: ["NH-10 km 78"],
    sensors: [
      { id: "S-MN-01", type: "Seismometer", status: "online", battery: 77 },
      { id: "S-MN-02", type: "Rain Gauge", status: "online", battery: 63 },
    ],
  },
  {
    id: "tripura-hills",
    name: "West Tripura Hills",
    district: "West Tripura",
    state: "Tripura",
    lat: 23.8315,
    lng: 91.2868,
    risk: "LOW",
    riskScore: 28,
    rainfall24h: 45,
    soilMoisture: 55,
    slope: 18,
    trigger: "Seasonal monitoring",
    lastUpdated: "2026-09-10T19:00:00+05:30",
    affectedPopulation: 1800,
    roadBlockages: [],
    sensors: [
      { id: "S-TR-01", type: "Rain Gauge", status: "online", battery: 89 },
    ],
  },
];

export const SHAP_FACTORS_24H: SHAPFactor[] = [
  { name: "24h Cumulative Rainfall", contribution: 0.82, value: "187", unit: "mm" },
  { name: "Soil Moisture Index", contribution: 0.68, value: "94", unit: "%" },
  { name: "Slope Angle", contribution: 0.54, value: "38", unit: "°" },
  { name: "Antecedent Rainfall (7d)", contribution: 0.47, value: "412", unit: "mm" },
  { name: "Lithology Index", contribution: 0.31, value: "0.79", unit: "" },
  { name: "Vegetation Cover (NDVI)", contribution: -0.22, value: "0.41", unit: "" },
  { name: "Distance to Fault", contribution: 0.18, value: "2.1", unit: "km" },
  { name: "Land Use Change", contribution: 0.14, value: "Cleared", unit: "" },
];

export const FORECAST_24H: ForecastPoint[] = [
  { hour: 0, risk: 92, rainfall: 18, confidence: 94 },
  { hour: 3, risk: 88, rainfall: 22, confidence: 91 },
  { hour: 6, risk: 85, rainfall: 28, confidence: 89 },
  { hour: 9, risk: 79, rainfall: 24, confidence: 86 },
  { hour: 12, risk: 76, rainfall: 19, confidence: 84 },
  { hour: 15, risk: 71, rainfall: 15, confidence: 82 },
  { hour: 18, risk: 68, rainfall: 12, confidence: 80 },
  { hour: 21, risk: 65, rainfall: 9, confidence: 78 },
  { hour: 24, risk: 62, rainfall: 7, confidence: 76 },
];

export const FORECAST_48H: ForecastPoint[] = [
  ...FORECAST_24H,
  { hour: 27, risk: 58, rainfall: 11, confidence: 72 },
  { hour: 30, risk: 62, rainfall: 18, confidence: 70 },
  { hour: 33, risk: 71, rainfall: 24, confidence: 67 },
  { hour: 36, risk: 78, rainfall: 31, confidence: 65 },
  { hour: 39, risk: 82, rainfall: 27, confidence: 63 },
  { hour: 42, risk: 75, rainfall: 20, confidence: 61 },
  { hour: 45, risk: 69, rainfall: 14, confidence: 59 },
  { hour: 48, risk: 63, rainfall: 9, confidence: 57 },
];

export const FORECAST_72H: ForecastPoint[] = [
  ...FORECAST_48H,
  { hour: 51, risk: 55, rainfall: 6, confidence: 53 },
  { hour: 54, risk: 48, rainfall: 8, confidence: 50 },
  { hour: 57, risk: 52, rainfall: 14, confidence: 48 },
  { hour: 60, risk: 64, rainfall: 22, confidence: 46 },
  { hour: 63, risk: 70, rainfall: 29, confidence: 44 },
  { hour: 66, risk: 67, rainfall: 24, confidence: 42 },
  { hour: 69, risk: 59, rainfall: 16, confidence: 40 },
  { hour: 72, risk: 51, rainfall: 10, confidence: 38 },
];

export const MOCK_ALERTS: AlertMessage[] = [
  {
    id: "ALT-001",
    channel: "SMS",
    recipient: "District Control Room, Dima Hasao",
    message: "⚠️ CRITICAL ALERT: Landslide probability 92% in Dima Hasao Highlands. Immediate evacuation of zones D1-D4. NH-27 km 341-348 CLOSED.",
    language: "en",
    status: "sent",
    timestamp: "2026-09-10T21:30:00+05:30",
  },
  {
    id: "ALT-002",
    channel: "WhatsApp",
    recipient: "SDRF Guwahati HQ",
    message: "🚨 SITREP: Dima Hasao risk score 92/100. Deploy 2 rescue teams. Resources: 3 vehicles, medical kit, 500m rope.",
    language: "en",
    status: "sent",
    timestamp: "2026-09-10T21:30:05+05:30",
  },
  {
    id: "ALT-003",
    channel: "Siren",
    recipient: "Village clusters D1, D2, D3",
    message: "Emergency evacuation siren activated — Cluster D1, D2, D3",
    language: "as",
    status: "sent",
    timestamp: "2026-09-10T21:31:00+05:30",
  },
  {
    id: "ALT-004",
    channel: "SMS",
    recipient: "NH-27 Traffic Control",
    message: "ROAD CLOSURE: NH-27 km 341-348 blocked due to landslide risk. Divert via Hojai-Lumding route.",
    language: "en",
    status: "sent",
    timestamp: "2026-09-10T21:32:00+05:30",
  },
  {
    id: "ALT-005",
    channel: "AppPush",
    recipient: "NER GeoWatch App users — 50km radius",
    message: "⚠️ Landslide warning active in your area. Check evacuation routes.",
    language: "as",
    status: "pending",
    timestamp: "2026-09-10T21:33:00+05:30",
  },
];

export const CITIZEN_REPORTS: CitizenReport[] = [
  {
    id: "CR-001",
    lat: 25.5812,
    lng: 93.0441,
    description: "Crack visible on hillside, ~30m long",
    severity: "severe",
    timestamp: "2026-09-10T20:45:00+05:30",
    verified: true,
    reporter: "USSD:+91-94360-XXXXX",
  },
  {
    id: "CR-002",
    lat: 25.0315,
    lng: 93.0121,
    description: "Road partially blocked by debris",
    severity: "moderate",
    timestamp: "2026-09-10T21:05:00+05:30",
    verified: false,
    reporter: "NER GeoWatch App",
  },
];

export const SITREP_DATA: SitrepData = {
  id: "SITREP-20260910-001",
  timestamp: "2026-09-10T21:30:00+05:30",
  generatedBy: "NER GeoWatch AI Engine v2.4",
  zones: [
    { zone: "Dima Hasao Highlands", risk: "CRITICAL", affected: 12400 },
    { zone: "NH-27 Lumding–Silchar", risk: "HIGH", affected: 8200 },
    { zone: "Champhai Valley", risk: "HIGH", affected: 5600 },
    { zone: "East Khasi Hills", risk: "MODERATE", affected: 3100 },
    { zone: "Mangan", risk: "MODERATE", affected: 2400 },
  ],
  actions: [
    "Evacuation of Dima Hasao clusters D1–D4 initiated",
    "SDRF Team Alpha deployed from Guwahati",
    "NH-27 km 341–348 closed to traffic",
    "IMD RED alert for Dima Hasao, Cachar districts",
    "NDRF standby in Silchar",
  ],
  resources: [
    { type: "SDRF Personnel", deployed: 48, available: 120 },
    { type: "Rescue Vehicles", deployed: 12, available: 32 },
    { type: "Medical Teams", deployed: 4, available: 10 },
    { type: "Helicopters", deployed: 1, available: 3 },
  ],
};

export const TRANSLATIONS = {
  en: {
    title: "NER GeoWatch",
    subtitle: "AI Early Warning & Landslide Risk Monitoring",
    critical: "CRITICAL",
    high: "HIGH",
    moderate: "MODERATE",
    low: "LOW",
    riskScore: "Risk Score",
    alert: "ALERT",
    evacuate: "EVACUATE NOW",
    forecast: "Risk Forecast",
    aiEngine: "AI Engine",
    citizenReport: "Report Hazard",
    sitrep: "Export SITREP",
    lowBandwidth: "Low-bandwidth mode active. USSD: *123# for alerts.",
  },
  as: {
    title: "NER GeoWatch",
    subtitle: "AI আগতীয়া সতৰ্কতা ব্যৱস্থা",
    critical: "সংকটজনক",
    high: "উচ্চ",
    moderate: "মধ্যম",
    low: "নিম্ন",
    riskScore: "বিপদৰ স্কোৰ",
    alert: "সতৰ্কতা",
    evacuate: "এতিয়াই উচ্ছেদ কৰক",
    forecast: "ভৱিষ্যদ্বাণী",
    aiEngine: "AI ইঞ্জিন",
    citizenReport: "বিপদ জনাওক",
    sitrep: "SITREP ৰপ্তানি",
    lowBandwidth: "নিম্ন-বেণ্ডৱিড্থ মোড সক্ৰিয়। USSD: *123# সতৰ্কতাৰ বাবে।",
  },
  hi: {
    title: "NER GeoWatch",
    subtitle: "AI प्रारंभिक चेतावनी प्रणाली",
    critical: "गंभीर",
    high: "उच्च",
    moderate: "मध्यम",
    low: "निम्न",
    riskScore: "जोखिम स्कोर",
    alert: "चेतावनी",
    evacuate: "अभी निकासी करें",
    forecast: "पूर्वानुमान",
    aiEngine: "AI इंजन",
    citizenReport: "खतरा रिपोर्ट करें",
    sitrep: "SITREP निर्यात",
    lowBandwidth: "कम-बैंडविड्थ मोड सक्रिय। USSD: *123# अलर्ट के लिए।",
  },
  bn: {
    title: "NER GeoWatch",
    subtitle: "AI আর্লি ওয়ার্নিং সিস্টেম",
    critical: "সংকটজনক",
    high: "উচ্চ",
    moderate: "মধ্যম",
    low: "নিম্ন",
    riskScore: "ঝুঁকির স্কোর",
    alert: "সতর্কতা",
    evacuate: "এখনই সরান",
    forecast: "পূর্বাভাস",
    aiEngine: "AI ইঞ্জিন",
    citizenReport: "বিপদ রিপোর্ট",
    sitrep: "SITREP রপ্তানি",
    lowBandwidth: "নিম্ন-ব্যান্ডউইডথ মোড সক্রিয়। USSD: *123# সতর্কতার জন্য।",
  },
};
